let min = 1,
    max= 10,
    guess_left = 3,
    winning_num = Math.floor(Math.random()*9) +1 ; // to be generated by math.random

const UImin_num = document.getElementById('min_num'),
      UImax_num = document.getElementById('max_num'),
      UIguess_input = document.getElementById('guess-input'),
      UIguess_btn =document.getElementById('guess-btn'),
      UIwrong_guess = document.getElementById('wrong_guess'),
      UIcorrect_guess = document.getElementById('correct_guess');
      UIgameOver = document.getElementById('game_Over');

      UImin_num.textContent = min;
      UImax_num.textContent = max;


      UIguess_btn.addEventListener('click',function(){
       guess_left-- ;
       if(guess_left > 0){
        let guess = parseInt(UIguess_input.value);
        if( !isNaN(guess) ||  guess >=1 && guess <=10)
         {
           switch(guess){
             case winning_num : 
             UIcorrect_guess.style.display = "block";
             setTimeout("toggleWinMessage()",2000); 
             UIguess_input.disabled = true;
             UIguess_input.style.border = "3px solid #00ff00"
             break;
             default :
             UIwrong_guess.style.display = "block";
             UIguess_input.style.border = "3px solid #9B1C31"
             setTimeout("toggleLostMessage()",2000);
             break;
             
           }
         }
       }


       else


       UIgameOver.style.display = "block";
       
      })

     function toggleWinMessage() {
      
      UIcorrect_guess.style.display = "none";
     }

     function toggleLostMessage() {

      UIwrong_guess.style.display = "none";
      

    }

